parameters:
    env(DATABASE_URL): ''
    env(ENV_database_host): mysql
    env(ENV_database_name): project
    env(ENV_database_password): project
    env(ENV_database_port): '3306'
    env(ENV_database_user): project
doctrine:
    dbal:
        driver: pdo_mysql
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: 'mysql://%env(ENV_database_user)%:%env(ENV_database_password)%@%env(ENV_database_host)%:%env(ENV_database_port)%/%env(ENV_database_name)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: App\Entity
                alias: App
