version: "2.1"

services:
    nginx:
        build:
          context: ./docker/nginx/
          args:
            server_name: "${SERVER_NAME}"
            app_php: "${APP_PHP}"
        ports:
          - "${NGINX_PORTS}"
        networks:
          - nw_internal
          - nw_external
        depends_on:
          - php
        volumes_from:
          - "php:ro"

    php:
        extends:
            file: docker-common.yml
            service: php
        build:
            context: "."
            dockerfile: Dockerfile-dev
        expose:
          - 9000
        networks:
          - nw_internal
        depends_on:
          - mysql
        volumes:
          - ".:/srv"
          - "/composer/vendor"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 8080:80
        networks:
          - nw_internal
        environment:
          PMA_ARBITRARY: "1"
          PMA_HOST: "mysql"
          PMA_USER: "root"
          PMA_PASSWORD: "${ENV_database_root_password}"
        depends_on:
          - mysql
        volumes:
          - /sessions

    mysql:
        extends:
            file: docker-common.yml
            service: mysql
        networks:
          - nw_internal

volumes:
    database:

networks:
    nw_external:
    nw_internal:
