version: "2.1"

services:
    nginx:
        image: "${CI_NGINX_IMAGE_WITH_TAG}"
        ports:
          - "80"
        restart: always
        networks:
            nw_internal:
            nw_external:
                ipv4_address: ${NETWORK_IP}
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
          - "assetsWebA:/srv/a:ro"
          - "assetsWebB:/srv/b:ro"
          - "assetsStorage:/srv/storage:ro"
        labels:
            docker-gen.host: ${SERVER_NAME}

    php:
        extends:
            file: docker-common.yml
            service: php
        image: "${CI_APP_IMAGE_WITH_TAG}"
        networks:
          - nw_internal
        restart: always
        volumes:
          - "assetsWebA:/srv/a:rw"
          - "assetsWebB:/srv/b:rw"
          - "assetsStorage:/srv/storage:rw"

    spare:
        extends: php

    mysql:
        extends:
            file: docker-common.yml
            service: mysql
        restart: always
        networks:
          - nw_internal

volumes:
    database:
    assetsWebA:
    assetsWebB:
    assetsStorage:

networks:
    nw_external:
        external:
            name: ${NETWORK_NAME}
    nw_internal:
